.DEFAULT_GOAL=main
main:
	sudo docker build -t minimal-www-server .
list:
	sudo docker images
run:
	# sudo docker run --name xxxxxxxxxxxx -d -p 80:80 minimal-www-server
	# sudo docker-compose up -d
	sudo docker-compose up --name abc
